FROM almalinux:9

#CMD ["ping", "yahoo.com"]

#ENTRYPOINT ["ping", "yahoo.com"]
ENTRYPOINT ["ping"] 
# cannpot overrode entrpoint
CMD ["yahoo.com"]
# we over ride cmd, at runtime

#dockr run -d image-name google.com